name: AutoMelinda! Main Script

on:
  schedule:
    - cron: 0 17 * * THU
    - cron: 0 17 * * TUE
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    - name: Run auto melinda!
      run: |
        yarn
        node index.js
